include:
    - project: "epi2melabs/ci-templates"
      file: "push-github.yaml"
    - project: "epi2melabs/ci-templates"
      file: "push-conda.yaml"
    - project: "epi2melabs/ci-templates"
      file: "snippets.yaml"

image: ${UBUNTUIMAGE}:20.04

variables:
    GIT_SUBMODULE_STRATEGY: recursive


stages:
    - release

conda:
    extends: .deploy-conda
    variables:
        RECIPEPATH: "../conda"
    before_script:
        - export CONDA_PKG=${CI_PROJECT_NAME}
        - mkdir conda-build
        - cd conda-build
